name: WanderingTrades

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sed "s/{BUILDID}/$GITHUB_RUN_NUMBER/g" build.gradle.kts > _build.gradle.kts; rm build.gradle.kts; mv _build.gradle.kts build.gradle.kts
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew clean shadowJar
    - run: mkdir staging && cp build/libs/WanderingTrades*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
